version: "3.9"

services:
  nafb:
    container_name: nafb
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    restart:
      always
    networks:
      - nafb

  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:latest
    restart:
      always
    networks:
      - nafb
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro

networks:
  nafb:
